# Generated by Django 5.2.7 on 2025-10-29 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_name', models.CharField(max_length=200)),
                ('active_ingredient', models.CharField(max_length=200)),
                ('strength', models.CharField(max_length=50)),
                ('form', models.CharField(choices=[('tablet', 'قرص'), ('capsule', 'كبسولة'), ('syrup', 'شراب'), ('injection', 'حقن'), ('cream', 'كريم')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('indications', models.TextField(blank=True)),
                ('contraindications', models.TextField(blank=True)),
                ('side_effects', models.TextField(blank=True)),
                ('times_prescribed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['trade_name'],
                'unique_together': {('trade_name', 'strength')},
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_date', models.DateField(auto_now_add=True)),
                ('diagnosis', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='appointments.booking')),
                ('doctor', models.ForeignKey(limit_choices_to={'type': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_prescriptions', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(limit_choices_to={'type': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-prescription_date'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('duration_days', models.IntegerField()),
                ('instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescription_items', to='pharmacy.medicinelibrary')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.prescription')),
            ],
        ),
    ]
