# Generated by Django 5.2.7 on 2025-10-29 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name_ar', models.CharField(max_length=200)),
                ('disease_name_en', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('chronic', 'مزمن'), ('infectious', 'معدي'), ('genetic', 'وراثي'), ('other', 'أخرى')], default='other', max_length=20)),
                ('symptoms', models.TextField(blank=True)),
                ('common_treatments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChronicDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('diagnosed_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(limit_choices_to={'type': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='chronic_diseases', to=settings.AUTH_USER_MODEL)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_cases', to='medical.commondisease')),
            ],
            options={
                'ordering': ['-diagnosed_date'],
                'unique_together': {('patient', 'disease')},
            },
        ),
    ]
