# Generated by Django 5.2.7 on 2025-10-29 20:49

import django.db.models.deletion
import etc.helper_functions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('procedure_details', models.TextField(blank=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('operation_date', models.DateField()),
                ('duration', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'مجدول'), ('in_progress', 'جاري التنفيذ'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation', to='appointments.booking')),
                ('doctor', models.ForeignKey(limit_choices_to={'type': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_operations', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(limit_choices_to={'type': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-operation_date'],
            },
        ),
        migrations.CreateModel(
            name='OperationMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'صورة'), ('video', 'فيديو'), ('audio', 'صوت'), ('document', 'مستند'), ('xray', 'أشعة'), ('other', 'أخرى')], max_length=20)),
                ('file_path', models.FileField(upload_to=etc.helper_functions.operation_media_uploader)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='operations.operation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
